### ISSUE TITLE
Use password hash

### ISSUE THREAD

**Issue by coreGreenberet** [flosoft/TeslaETA#5]
Sending passwords in plaintext is dangerous. 
Please use a (salted) hash algorithm for that. E.g. sha256
https://github.com/flosoft/TeslaETA/blob/4fe05b360ddfa65e374585d817caf9466ad55e81/app.py#L61

**Comment by flosoft** [comment]
I don't really see any issue here. You're either running this locally or over HTTPS, so sending plaintext is not an issue. The vast majority of websites send the password formdata unhashed over secure channels.
